// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntzepeagkmlbhzfoxwnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50emVwZWFna21sYmh6Zm94d252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzY5NTgsImV4cCI6MjA2NjYxMjk1OH0.Yxr5DFvi3k9hTG4EN6uu_E6fYMLQAzbt079JCJx-ASM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);